### ISSUE TITLE
README should mention package is deprecated

### ISSUE THREAD

**Issue by VichoReyes** [ekampf/gql#31]
According to #22 gql-next is deprecated in favor of gql v3. The readme should also mention that to avoid confusion.

**Comment by Cito** [comment]
My comment in #22 was a bit misleading, so I removed it.  The name "gql-next" has nothing to do with GraphQL-core-next (as GraphQL-core v3 was called earlier). It was rather a very interesting, type-safe, alternative approach for creating a Python GraphQL client, very different from the original gql implementation. The name "gql-next" was chosen because it was meant to eventually/potentially replace [gql](https://github.com/graphql-python/gql). However, since then no further work happened in this project, while gql was actively maintained and further developed and is now based on GraphQL-core 3.

This project should be considered more like an experiment and an invitation to continue development and experimentation in this direction. I agree this should be reflected in the README and the name and title should be changed. It's not good to have two projects with the exact same title. But I would want to leave this to the creator of this project @ekampf.

**Comment by ekampf** [comment]
I agree!
Added deprecation notice to the README

**Comment by Fraggle** [comment]
@ekampf I was particulary interested by the ability to generate the types via the cli. I can't figure out another client providing this feature for python. Do you have a suggestion ?
